%% Car Recommendation Expert Rules
%% CPSC 583 Project - Potvin, Jakhete, Kapadia
%%
%% This file contains the actual reasoning rules for classifying cars.
%% Facts are loaded from car_facts.pl (generated by Python)
%%
%% Fact format: car(Make, Model, Year, Price, Safety, Reliability, Mileage)

:- dynamic car/7.

%% ===========================================
%% Basic property predicates
%% These define what makes a car have certain qualities
%% ===========================================

% High reliability = score >= 0.8
high_reliability(car(_, _, _, _, _, Reliability, _)) :-
    Reliability >= 0.8.

% High safety = rating >= 4.5 stars
high_safety(car(_, _, _, _, Safety, _, _)) :-
    Safety >= 4.5.

% Affordable = under $25k
affordable(car(_, _, _, Price, _, _, _)) :-
    Price =< 25000.

% Budget friendly = under $18k
budget_friendly(car(_, _, _, Price, _, _, _)) :-
    Price =< 18000.

% Low mileage = under 50k miles
low_mileage(car(_, _, _, _, _, _, Mileage)) :-
    Mileage =< 50000.

% Recent model = 2019 or newer
recent_model(car(_, _, Year, _, _, _, _)) :-
    Year >= 2019.

% Good resale brands (based on industry data)
good_resale_brand(car(Make, _, _, _, _, _, _)) :-
    member(Make, ['TOYOTA', 'HONDA', 'LEXUS', 'SUBARU', 'MAZDA']).

%% ===========================================
%% Classification rules
%% These combine basic predicates into categories
%% ===========================================

% Excellent choice - hits all the major criteria
% A car you can buy with confidence
excellent_choice(Car) :-
    high_reliability(Car),
    high_safety(Car),
    recent_model(Car),
    low_mileage(Car).

% Good value - reliable and safe but affordable
% Best bang for your buck
good_value(Car) :-
    high_reliability(Car),
    high_safety(Car),
    affordable(Car).

% Family car - prioritizes safety
% Good for transporting kids
family_car(Car) :-
    high_safety(Car),
    high_reliability(Car),
    Car = car(_, _, _, _, Safety, _, _),
    Safety >= 4.5.

% Reliable commuter - will get you to work without issues
reliable_commuter(Car) :-
    high_reliability(Car),
    low_mileage(Car),
    affordable(Car).

% Budget pick - cheapest options that are still decent
budget_pick(Car) :-
    budget_friendly(Car),
    Car = car(_, _, _, _, Safety, Reliability, _),
    Safety >= 3.5,
    Reliability >= 0.6.

% Good investment - will hold value
good_investment(Car) :-
    good_resale_brand(Car),
    high_reliability(Car),
    recent_model(Car),
    low_mileage(Car).

%% ===========================================
%% Helper predicates for explanations
%% ===========================================

% Get all categories a car belongs to
car_categories(Car, Categories) :-
    findall(Cat, (
        (excellent_choice(Car), Cat = excellent_choice);
        (good_value(Car), Cat = good_value);
        (family_car(Car), Cat = family_car);
        (reliable_commuter(Car), Cat = reliable_commuter);
        (budget_pick(Car), Cat = budget_pick);
        (good_investment(Car), Cat = good_investment)
    ), Categories).

% Get positive attributes
car_strengths(Car, Strengths) :-
    findall(Str, (
        (high_reliability(Car), Str = 'highly reliable');
        (high_safety(Car), Str = 'excellent safety rating');
        (affordable(Car), Str = 'affordable price');
        (low_mileage(Car), Str = 'low mileage');
        (recent_model(Car), Str = 'recent model year');
        (good_resale_brand(Car), Str = 'good resale value brand')
    ), Strengths).

% Identify potential concerns
car_concerns(Car, Concerns) :-
    findall(Con, (
        (\+ high_reliability(Car), Con = 'lower reliability - budget for repairs');
        (\+ high_safety(Car), Con = 'safety rating below 4.5 stars');
        (Car = car(_, _, _, _, _, _, Mileage), Mileage > 80000,
         Con = 'higher mileage vehicle')
    ), Concerns).

%% ===========================================
%% Query helpers
%% ===========================================

% Find all cars in a category
find_category(Category, Cars) :-
    findall(Car, (
        car(Make, Model, Year, Price, Safety, Rel, Miles),
        Car = car(Make, Model, Year, Price, Safety, Rel, Miles),
        call(Category, Car)
    ), Cars).

% Compare two cars
better_than(Car1, Car2) :-
    Car1 = car(_, _, _, Price1, Safety1, Rel1, Miles1),
    Car2 = car(_, _, _, Price2, Safety2, Rel2, Miles2),
    % car1 is better if it beats car2 on most metrics
    (Safety1 > Safety2 ; (Safety1 =:= Safety2, Rel1 > Rel2)),
    (Rel1 >= Rel2),
    (Miles1 =< Miles2),
    (Price1 =< Price2).
